add Chrome

diff --git a/.github/workflows/deploy.yaml b/.github/workflows/deploy.yaml
--- a/.github/workflows/deploy.yaml
+++ b/.github/workflows/deploy.yaml
@@ -16,10 +16,11 @@ jobs:
       - name: Checkout code
         uses: actions/checkout@v3
 
-      - name: Download Chrome
-        run: wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
       - name: Install Chrome
-        run: sudo dpkg -i google-chrome-stable_current_amd64.deb
+        run: |
+          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
+          udo dpkg -i google-chrome-stable_current_amd64.deb
+
       - name: Fix missing dependencies
         run: sudo apt-get install -f
 
@@ -32,18 +33,16 @@ jobs:
         run: |
           pip install -r requirements.txt
 
-      - name: Set up Chrome
-        run: |
-          sudo apt-get update
-          sudo apt-get install -y wget unzip
-          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
-          sudo dpkg -i google-chrome-stable_current_amd64.deb
-          sudo apt-get install -f
-
       - name: Set up ChromeDriver
         run: |
           CHROME_VERSION=$(google-chrome --version | grep -oE '[0-9]+.[0-9]+.[0-9]+.[0-9]+')
-          CHROMEDRIVER_VERSION=$(curl -sS chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROME_VERSION)
+          CHROMEDRIVER_VERSION=$(curl -sS chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROME_VERSION) || echo "Latest version not found")
+          
+          if [[ "$CHROMEDRIVER_VERSION" == "Latest version not found" ]]; then
+          echo "Using the latest ChromeDriver version"
+          CHROMEDRIVER_VERSION=$(curl -sS "https://chromedriver.storage.googleapis.com/LATEST_RELEASE")
+          fi
+          
           wget https://chromedriver.storage.googleapis.com/$CHROMEDRIVER_VERSION/chromedriver_linux64.zip
           unzip chromedriver_linux64.zip
           sudo mv chromedriver /usr/local/bin/
