add Chrome

diff --git a/.github/workflows/deploy.yaml b/.github/workflows/deploy.yaml
--- a/.github/workflows/deploy.yaml
+++ b/.github/workflows/deploy.yaml
@@ -36,12 +36,22 @@ jobs:
       - name: Set up ChromeDriver
         run: |
           CHROME_VERSION=$(google-chrome --version | grep -oE '[0-9]+.[0-9]+.[0-9]+.[0-9]+')
+
+          if [ -z "$CHROME_VERSION" ]; then
+            echo "Failed to get Chrome version"
+            exit 1
+          fi
+
+          echo "Chrome version: $CHROME_VERSION"
+
           CHROMEDRIVER_VERSION=$(curl -sS "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROME_VERSION" || echo "Latest version not found")
 
           if [[ "$CHROMEDRIVER_VERSION" == "Latest version not found" ]]; then
             echo "Using the latest ChromeDriver version"
             CHROMEDRIVER_VERSION=$(curl -sS "https://chromedriver.storage.googleapis.com/LATEST_RELEASE")
           fi
+
+          echo "ChromeDriver version: $CHROMEDRIVER_VERSION"
 
           wget https://chromedriver.storage.googleapis.com/$CHROMEDRIVER_VERSION/chromedriver_linux64.zip
           unzip chromedriver_linux64.zip
