add Chrome

diff --git a/.github/workflows/deploy.yaml b/.github/workflows/deploy.yaml
--- a/.github/workflows/deploy.yaml
+++ b/.github/workflows/deploy.yaml
@@ -35,14 +35,14 @@ jobs:
 
       - name: Set up ChromeDriver
         run: |
-          CHROME_VERSION=google-chrome --version | grep -oE '[0-9]+.[0-9]+.[0-9]+.[0-9]+'
-          CHROMEDRIVER_VERSION=$(curl -sS chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROME_VERSION) || echo "Latest version not found")
-          
+          CHROME_VERSION=$(google-chrome --version | grep -oE '[0-9]+.[0-9]+.[0-9]+.[0-9]+')
+          CHROMEDRIVER_VERSION=$(curl -sS "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROME_VERSION" || echo "Latest version not found")
+
           if [[ "$CHROMEDRIVER_VERSION" == "Latest version not found" ]]; then
-          echo "Using the latest ChromeDriver version"
-          CHROMEDRIVER_VERSION=$(curl -sS "https://chromedriver.storage.googleapis.com/LATEST_RELEASE")
+            echo "Using the latest ChromeDriver version"
+            CHROMEDRIVER_VERSION=$(curl -sS "https://chromedriver.storage.googleapis.com/LATEST_RELEASE")
           fi
-          
+
           wget https://chromedriver.storage.googleapis.com/$CHROMEDRIVER_VERSION/chromedriver_linux64.zip
           unzip chromedriver_linux64.zip
           sudo mv chromedriver /usr/local/bin/
